/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.opennlp.grpc.webapp;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Parses every request body the workbench can send through the gateway's real JSON route
 * table and its strict protobuf JSON parser.
 *
 * <p>The fixtures under {@code opennlp-grpc-webapp-default/test/fixtures/requests} are
 * generated by the front end's own builders and API client (see
 * {@code test/request-fixtures.test.ts}); a fixture's file name, up to an optional
 * {@code --n} suffix, is the route it is sent to. A field the front end renames without
 * the proto, or an enum it misspells, fails here instead of as a 400 in a user's browser.</p>
 */
class FrontEndRequestFixtureTest {

  /** Where the reactor keeps the front end's fixtures, relative to this module. */
  private static final Path FIXTURES = Path.of(System.getProperty("basedir", "."))
      .resolve("../opennlp-grpc-webapp-default/test/fixtures/requests").normalize();

  @TestFactory
  Stream<DynamicTest> everyFrontEndRequestParsesThroughTheGateway() throws IOException {
    assertTrue(Files.isDirectory(FIXTURES), "front-end fixtures missing at " + FIXTURES);
    final List<Path> fixtures;
    try (Stream<Path> files = Files.list(FIXTURES)) {
      fixtures = files.filter(file -> file.getFileName().toString().endsWith(".json"))
          .sorted().toList();
    }
    assertTrue(fixtures.size() >= 16, "expected the full fixture set, found " + fixtures.size());
    final GrpcJsonApi api = new GrpcJsonApi(new EmptyAnalysisRpc(), new EmptySearchRpc(),
        new EmptyVocabularyRpc(), new EmptyTrainingRpc());
    return fixtures.stream().map(fixture -> DynamicTest.dynamicTest(
        fixture.getFileName().toString(), () -> assertParses(api, fixture)));
  }

  @Test
  void aMisspelledFieldOrEnumIsRejectedNotIgnored() {
    final GrpcJsonApi api = new GrpcJsonApi(new EmptyAnalysisRpc(), new EmptySearchRpc(),
        new EmptyVocabularyRpc(), new EmptyTrainingRpc());
    final WebHttpResponse field = api.handle("POST", "/api/v1/search",
        "{\"indexId\":\"x\",\"query\":{\"rawTxt\":\"q\"},\"topK\":1}"
            .getBytes(StandardCharsets.UTF_8));
    assertEquals(400, field.status(), "an unknown field must not parse");
    final WebHttpResponse value = api.handle("POST", "/api/v1/index-documents",
        "{\"displayName\":\"x\",\"provider\":{\"standard\":\"STANDARD_SEARCH_PROVIDER_FLAT\"}}"
            .getBytes(StandardCharsets.UTF_8));
    assertEquals(400, value.status(), "an unknown enum value must not parse");
  }

  /**
   * Sends one fixture to its route and requires the gateway to have parsed it.
   *
   * @param api The gateway route table over empty adapters.
   * @param fixture The fixture file.
   * @throws IOException If the fixture cannot be read.
   */
  private static void assertParses(GrpcJsonApi api, Path fixture) throws IOException {
    final String route = "/api/v1/" + routeName(fixture.getFileName().toString());
    final WebHttpResponse response =
        api.handle("POST", route, Files.readAllBytes(fixture));
    assertEquals(200, response.status(), () -> fixture.getFileName() + " to " + route + ": "
        + new String(response.body(), StandardCharsets.UTF_8));
  }

  /**
   * Strips the {@code .json} suffix and an optional {@code --n} ordinal from a fixture name.
   *
   * @param fileName The fixture file name.
   * @return The route name.
   */
  static String routeName(String fileName) {
    final String base = fileName.substring(0, fileName.length() - ".json".length());
    final int ordinal = base.indexOf("--");
    return ordinal < 0 ? base : base.substring(0, ordinal);
  }
}
