/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.opennlp.grpc.vocabulary;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import com.google.protobuf.Timestamp;
import opennlp.embeddings.corpus.TermCount;
import opennlp.embeddings.corpus.VocabularyLearner;
import org.apache.opennlp.grpc.v1.DictionaryArtifactDescriptor;
import org.apache.opennlp.grpc.v1.ImportDictionaryStart;
import org.apache.opennlp.grpc.v1.LearnVocabularyStart;
import org.apache.opennlp.grpc.v1.OpenNlpDocument;
import org.apache.opennlp.grpc.v1.VocabularyArtifactDescriptor;
import org.apache.opennlp.grpc.vocabulary.store.ArtifactDigests;
import org.apache.opennlp.grpc.spi.vocabulary.VocabularyStore;
import org.apache.opennlp.grpc.vocabulary.store.VocabularyStores;
import org.apache.opennlp.grpc.spi.vocabulary.DictionaryFormatProvider;

/**
 * Bounded, atomic store for imported dictionaries and learned vocabulary tables.
 *
 * <p>All artifact ids are generated by the server, and callers never select storage
 * locations. Durability is delegated to a {@link VocabularyStore} selected by the
 * scheme of the configured artifact root, the filesystem store by default; artifacts
 * become visible only through the store's atomic commit, so readers never observe a
 * partial artifact.</p>
 */
public final class VocabularyArtifactStore {

  /** Default maximum encoded dictionary input size. */
  static final int DEFAULT_MAX_DICTIONARY_BYTES = 64 * 1024 * 1024;
  /** Default maximum number of normalized dictionary entries. */
  static final int DEFAULT_MAX_DICTIONARY_ENTRIES = 1_000_000;
  /** Default maximum documents in one vocabulary build. */
  static final int DEFAULT_MAX_CORPUS_DOCUMENTS = 100_000;
  /** Default maximum UTF-8 corpus text bytes in one vocabulary build. */
  static final int DEFAULT_MAX_CORPUS_BYTES = 100 * 1024 * 1024;
  /** Default maximum vocabulary terms, including dictionary terms. */
  static final int DEFAULT_MAX_VOCABULARY_TERMS = 1_000_000;
  /** Default maximum dictionary imports and vocabulary builds admitted at once. */
  static final int DEFAULT_MAX_CONCURRENT_WRITES = 1;

  private static final int MAX_DICTIONARY_BYTES_LIMIT = 1_073_741_824;
  private static final int MAX_DICTIONARY_ENTRIES_LIMIT = 10_000_000;
  private static final int MAX_CORPUS_DOCUMENTS_LIMIT = 1_000_000;
  private static final int MAX_CORPUS_BYTES_LIMIT = 1_073_741_824;
  private static final int MAX_VOCABULARY_TERMS_LIMIT = 10_000_000;
  private static final int MAX_CONCURRENT_WRITES_LIMIT = 32;
  private static final int MAX_ENTRY_BYTES = 1_048_576;
  static final String ARTIFACT_ROOT_KEY = "vocabulary.artifact_root";
  private static final String DICTIONARIES_KIND = "dictionaries";
  private static final String VOCABULARIES_KIND = "vocabularies";
  private static final String DICTIONARY_DATA = "entries.tsv";
  private static final String DICTIONARY_DESCRIPTOR = "dictionary.pb";
  private static final String VOCABULARY_DATA = "vocabulary.tsv";
  private static final String VOCABULARY_DESCRIPTOR = "vocabulary.pb";

  private final VocabularyStore store;
  private final DictionaryFormatRegistry formats;
  private final int maxDictionaryBytes;
  private final int maxDictionaryEntries;
  private final int maxCorpusDocuments;
  private final int maxCorpusBytes;
  private final int maxVocabularyTerms;
  private final int maxConcurrentWrites;
  private final Map<String, DictionaryArtifactDescriptor> dictionaries =
      new ConcurrentHashMap<>();
  private final Map<String, VocabularyArtifactDescriptor> vocabularies =
      new ConcurrentHashMap<>();

  /** Creates the store and verifies every artifact already published in it. */
  private VocabularyArtifactStore(
      VocabularyStore store,
      DictionaryFormatRegistry formats,
      int maxDictionaryBytes,
      int maxDictionaryEntries,
      int maxCorpusDocuments,
      int maxCorpusBytes,
      int maxVocabularyTerms,
      int maxConcurrentWrites) throws IOException {
    this.store = store;
    this.formats = formats;
    this.maxDictionaryBytes = maxDictionaryBytes;
    this.maxDictionaryEntries = maxDictionaryEntries;
    this.maxCorpusDocuments = maxCorpusDocuments;
    this.maxCorpusBytes = maxCorpusBytes;
    this.maxVocabularyTerms = maxVocabularyTerms;
    this.maxConcurrentWrites = maxConcurrentWrites;
    if (store != null) {
      loadExistingArtifacts();
    }
  }

  /**
   * Creates a disabled or enabled store from server configuration. The artifact root
   * is a plain directory path or a URI whose scheme selects the durable store, see
   * {@link VocabularyStores#open(String)}.
   *
   * @param configuration Server configuration map.
   * @param formats Available dictionary format registry.
   * @return Configured store.
   * @throws IOException If an enabled artifact root cannot be created or verified.
   * @throws IllegalArgumentException If a configured limit or the root is invalid.
   */
  public static VocabularyArtifactStore fromConfiguration(
      Map<String, String> configuration, DictionaryFormatRegistry formats) throws IOException {
    if (configuration == null) {
      throw new IllegalArgumentException("configuration must not be null");
    }
    if (formats == null) {
      throw new IllegalArgumentException("formats must not be null");
    }
    final String configuredRoot = configuration.get(ARTIFACT_ROOT_KEY);
    final VocabularyStore store = configuredRoot == null || configuredRoot.isBlank()
        ? null : VocabularyStores.open(configuredRoot);
    return new VocabularyArtifactStore(
        store,
        formats,
        configuredPositiveInt(configuration, "vocabulary.max_dictionary_bytes",
            DEFAULT_MAX_DICTIONARY_BYTES, MAX_DICTIONARY_BYTES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_dictionary_entries",
            DEFAULT_MAX_DICTIONARY_ENTRIES, MAX_DICTIONARY_ENTRIES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_corpus_documents",
            DEFAULT_MAX_CORPUS_DOCUMENTS, MAX_CORPUS_DOCUMENTS_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_corpus_bytes",
            DEFAULT_MAX_CORPUS_BYTES, MAX_CORPUS_BYTES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_vocabulary_terms",
            DEFAULT_MAX_VOCABULARY_TERMS, MAX_VOCABULARY_TERMS_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_concurrent_writes",
            DEFAULT_MAX_CONCURRENT_WRITES, MAX_CONCURRENT_WRITES_LIMIT));
  }

  /**
   * Returns whether write and download operations have a configured artifact root.
   *
   * @return Whether artifact writes are enabled.
   */
  public boolean writesEnabled() {
    return store != null;
  }

  /** @return Maximum encoded bytes accepted by one dictionary import. */
  int maxDictionaryBytes() {
    return maxDictionaryBytes;
  }

  /** @return Maximum normalized entries accepted by one dictionary import. */
  int maxDictionaryEntries() {
    return maxDictionaryEntries;
  }

  /**
   * Returns the maximum documents accepted by one vocabulary build.
   *
   * @return Per-build document limit.
   */
  public int maxCorpusDocuments() {
    return maxCorpusDocuments;
  }

  /**
   * Returns the maximum UTF-8 corpus bytes accepted by one vocabulary build.
   *
   * @return Per-build UTF-8 byte limit.
   */
  public int maxCorpusBytes() {
    return maxCorpusBytes;
  }

  /** @return Maximum total terms accepted in one learned vocabulary. */
  int maxVocabularyTerms() {
    return maxVocabularyTerms;
  }

  /** @return Maximum dictionary imports and vocabulary builds admitted at once. */
  int maxConcurrentWrites() {
    return maxConcurrentWrites;
  }

  /**
   * Imports one complete bounded dictionary payload and publishes its canonical representation.
   *
   * @param start Import metadata and format selector.
   * @param encoded Complete encoded bytes.
   * @return Published artifact descriptor.
   * @throws IOException If parsing or atomic publication fails.
   * @throws IllegalArgumentException If the metadata, format, or payload bounds are invalid.
   */
  DictionaryArtifactDescriptor importDictionary(
      ImportDictionaryStart start, byte[] encoded) throws IOException {
    requireEnabled();
    validateImportStart(start);
    if (encoded == null) {
      throw new IllegalArgumentException("dictionary data must not be null");
    }
    if (encoded.length > maxDictionaryBytes) {
      throw new IllegalArgumentException("dictionary bytes " + encoded.length
          + " exceed configured maximum " + maxDictionaryBytes);
    }
    final DictionaryFormatProvider provider = formats.require(start.getFormat());
    final Map<String, DictionaryEntryData> decoded = new LinkedHashMap<>();
    try (InputStream input = new ByteArrayInputStream(encoded)) {
      provider.read(input, (headword, definition) -> {
        final DictionaryEntryData entry;
        try {
          entry = new DictionaryEntryData(headword, definition);
        } catch (IllegalArgumentException e) {
          throw new IOException("Invalid dictionary entry: " + e.getMessage(), e);
        }
        final int entryBytes = utf8Length(entry.headword()) + utf8Length(entry.definition());
        if (entryBytes > MAX_ENTRY_BYTES) {
          throw new IOException("Dictionary entry exceeds " + MAX_ENTRY_BYTES + " UTF-8 bytes");
        }
        decoded.putIfAbsent(entry.headword(), entry);
        if (decoded.size() > maxDictionaryEntries) {
          throw new IOException("dictionary entries exceed configured maximum "
              + maxDictionaryEntries);
        }
      });
    }
    if (decoded.isEmpty()) {
      throw new IllegalArgumentException("dictionary must contain at least one entry");
    }

    final String artifactId = "dictionary-" + UUID.randomUUID();
    try (VocabularyStore.ArtifactWriter writer = store.write(DICTIONARIES_KIND, artifactId)) {
      final ArtifactDigests.HashingOutputStream data =
          new ArtifactDigests.HashingOutputStream(writer.entry(DICTIONARY_DATA));
      try (data) {
        writeDictionary(new ArrayList<>(decoded.values()), data);
      }
      final DictionaryArtifactDescriptor.Builder descriptor = DictionaryArtifactDescriptor
          .newBuilder()
          .setArtifactId(artifactId)
          .setDisplayName(start.getDisplayName())
          .setFormat(start.getFormat())
          .setEntryCount(decoded.size())
          .setArtifactHash(data.hexDigest())
          .setByteSize(checkedUint32(data.count(), "dictionary artifact bytes"))
          .setProvenanceSummary(start.getProvenanceSummary())
          .setCreatedAt(now());
      if (start.hasSourceUri()) {
        descriptor.setSourceUri(start.getSourceUri());
      }
      if (start.hasLicenseName()) {
        descriptor.setLicenseName(start.getLicenseName());
      }
      if (start.hasLicenseUri()) {
        descriptor.setLicenseUri(start.getLicenseUri());
      }
      final DictionaryArtifactDescriptor result = descriptor.build();
      try (OutputStream out = writer.entry(DICTIONARY_DESCRIPTOR)) {
        result.writeTo(out);
      }
      writer.commit();
      dictionaries.put(artifactId, result);
      return result;
    }
  }

  /**
   * Learns and atomically publishes a vocabulary over the supplied document shapes.
   *
   * @param start Learning configuration and dictionary identity.
   * @param documents Corpus documents whose raw text is counted.
   * @return Published vocabulary descriptor.
   * @throws IOException If artifact reading or publication fails.
   * @throws IllegalArgumentException If the controls, dictionary id, or corpus are invalid.
   */
  public VocabularyArtifactDescriptor learnVocabulary(
      LearnVocabularyStart start, List<OpenNlpDocument> documents) throws IOException {
    requireEnabled();
    validateLearningStart(start);
    if (documents == null) {
      throw new IllegalArgumentException("corpus documents must not be null");
    }
    if (documents.isEmpty()) {
      throw new IllegalArgumentException("corpus must contain at least one document");
    }
    if (documents.size() > maxCorpusDocuments) {
      throw new IllegalArgumentException("corpus documents " + documents.size()
          + " exceed configured maximum " + maxCorpusDocuments);
    }
    final List<String> texts = new ArrayList<>(documents.size());
    long corpusBytes = 0;
    for (OpenNlpDocument document : documents) {
      if (document == null) {
        throw new IllegalArgumentException("corpus documents must not contain null");
      }
      if (document.getRawText().isBlank()) {
        throw new IllegalArgumentException("corpus document raw_text must not be blank");
      }
      corpusBytes += utf8Length(document.getRawText());
      if (corpusBytes > maxCorpusBytes) {
        throw new IllegalArgumentException("corpus bytes " + corpusBytes
            + " exceed configured maximum " + maxCorpusBytes);
      }
      texts.add(document.getRawText());
    }

    final String dictionaryArtifactId = start.getDictionaryArtifactId();
    final List<String> headwords = dictionaryArtifactId.isEmpty()
        ? List.of() : readDictionaryHeadwords(dictionaryArtifactId);
    final List<TermCount> terms = new VocabularyLearner(
        start.getMinFrequency(), start.getMaxTerms()).learn(texts, headwords);
    if (terms.size() > maxVocabularyTerms) {
      throw new IllegalArgumentException("learned vocabulary terms " + terms.size()
          + " exceed configured maximum " + maxVocabularyTerms);
    }
    final long dictionaryTerms = terms.stream().filter(TermCount::fromDictionary).count();
    final String artifactId = "vocabulary-" + UUID.randomUUID();
    // TermCount writes its interchange form to a file in local scratch
    // first and streams into the store from there.
    final Path scratch = Files.createTempFile("vocabulary-", ".tsv");
    try {
      TermCount.writeTsv(terms, scratch);
      try (VocabularyStore.ArtifactWriter writer = store.write(VOCABULARIES_KIND, artifactId)) {
        final ArtifactDigests.HashingOutputStream data =
            new ArtifactDigests.HashingOutputStream(writer.entry(VOCABULARY_DATA));
        try (data; InputStream input = Files.newInputStream(scratch)) {
          input.transferTo(data);
        }
        final VocabularyArtifactDescriptor result = VocabularyArtifactDescriptor.newBuilder()
            .setArtifactId(artifactId)
            .setDisplayName(start.getDisplayName())
            .setDictionaryArtifactId(start.getDictionaryArtifactId())
            .setTermCount(terms.size())
            .setDictionaryTermCount(checkedUint32(dictionaryTerms, "dictionary term count"))
            .setCorpusTermCount(checkedUint32(terms.size() - dictionaryTerms, "corpus term count"))
            .setMinFrequency(start.getMinFrequency())
            .setMaxTerms(start.getMaxTerms())
            .setArtifactHash(data.hexDigest())
            .setByteSize(checkedUint32(data.count(), "vocabulary artifact bytes"))
            .setProvenanceSummary(start.getProvenanceSummary())
            .setCreatedAt(now())
            .build();
        try (OutputStream out = writer.entry(VOCABULARY_DESCRIPTOR)) {
          result.writeTo(out);
        }
        writer.commit();
        vocabularies.put(artifactId, result);
        return result;
      }
    } finally {
      Files.deleteIfExists(scratch);
    }
  }

  /**
   * Resolves one dictionary descriptor.
   *
   * @param artifactId Server-owned artifact id.
   * @return Descriptor.
   * @throws IllegalArgumentException If the id is invalid or unknown.
   */
  public DictionaryArtifactDescriptor requireDictionary(String artifactId) {
    requireArtifactId(artifactId, "dictionary");
    final DictionaryArtifactDescriptor descriptor = dictionaries.get(artifactId);
    if (descriptor == null) {
      throw new UnknownVocabularyArtifactException(
          "Unknown dictionary artifact '" + artifactId + "'");
    }
    return descriptor;
  }

  /**
   * Lists imported dictionaries available to seed vocabulary learning.
   *
   * @return Imported dictionaries in stable artifact-id order.
   */
  public List<DictionaryArtifactDescriptor> listDictionaries() {
    return List.copyOf(dictionaries.values());
  }

  /**
   * Lists learned vocabularies available for distillation or a collection watch.
   *
   * @return Published vocabularies in ascending artifact-id order.
   */
  public List<VocabularyArtifactDescriptor> listVocabularies() {
    return vocabularies.values().stream()
        .sorted(Comparator.comparing(VocabularyArtifactDescriptor::getArtifactId))
        .toList();
  }

  /**
   * Resolves one vocabulary descriptor.
   *
   * @param artifactId Server-owned artifact id.
   * @return Descriptor.
   * @throws IllegalArgumentException If the id is invalid or unknown.
   */
  public VocabularyArtifactDescriptor requireVocabulary(String artifactId) {
    requireArtifactId(artifactId, "vocabulary");
    final VocabularyArtifactDescriptor descriptor = vocabularies.get(artifactId);
    if (descriptor == null) {
      throw new UnknownVocabularyArtifactException(
          "Unknown vocabulary artifact '" + artifactId + "'");
    }
    return descriptor;
  }

  /**
   * Deletes one published vocabulary artifact.
   *
   * <p>Durable storage is deleted before the in-process descriptor so a failed
   * deletion never leaves a published artifact hidden only from this process.</p>
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return {@code true} when the vocabulary existed and was deleted.
   * @throws IOException If durable deletion fails.
   * @throws IllegalStateException If no artifact root is configured.
   * @throws IllegalArgumentException If the artifact id is malformed.
   */
  public boolean deleteVocabulary(String artifactId) throws IOException {
    requireEnabled();
    requireArtifactId(artifactId, "vocabulary");
    if (!vocabularies.containsKey(artifactId)) {
      return false;
    }
    store.delete(VOCABULARIES_KIND, artifactId);
    vocabularies.remove(artifactId);
    return true;
  }

  /**
   * Reads and verifies the exact TSV bytes for one learned vocabulary.
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return Exact artifact bytes.
   * @throws IOException If reading or integrity verification fails.
   * @throws IllegalArgumentException If the artifact id is invalid or unknown.
   */
  byte[] readVocabulary(String artifactId) throws IOException {
    try (InputStream input = openVocabulary(artifactId)) {
      return input.readAllBytes();
    }
  }

  /**
   * Opens a verified stream over the exact TSV bytes for one learned vocabulary.
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return Verified artifact stream. The caller must close it.
   * @throws IOException If opening or integrity verification fails.
   * @throws IllegalArgumentException If the artifact id is invalid or unknown.
   */
  public InputStream openVocabulary(String artifactId) throws IOException {
    requireEnabled();
    final VocabularyArtifactDescriptor descriptor = requireVocabulary(artifactId);
    verify(VOCABULARIES_KIND, artifactId, VOCABULARY_DATA,
        descriptor.getByteSize(), descriptor.getArtifactHash());
    return store.read(VOCABULARIES_KIND, artifactId, VOCABULARY_DATA);
  }

  /**
   * One parsed vocabulary term row.
   *
   * @param term Term text; multiword terms are joined by single spaces.
   * @param count Occurrence count recorded at learning time.
   */
  public record TermRow(String term, long count) {
  }

  /**
   * Reads and parses the term rows of one learned vocabulary in stored order.
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return Immutable term rows in artifact order.
   * @throws IOException If reading, integrity verification, or parsing fails.
   * @throws IllegalArgumentException If the artifact id is invalid or unknown.
   */
  public List<TermRow> readVocabularyTermRows(String artifactId) throws IOException {
    final List<TermRow> rows = new ArrayList<>();
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(
        openVocabulary(artifactId), StandardCharsets.UTF_8))) {
      String line;
      while ((line = reader.readLine()) != null) {
        final int firstTab = line.indexOf('\t');
        final int secondTab = firstTab < 0 ? -1 : line.indexOf('\t', firstTab + 1);
        if (firstTab <= 0 || secondTab < 0) {
          throw new IOException("Corrupt vocabulary artifact '" + artifactId + "'");
        }
        final long count;
        try {
          count = Long.parseLong(line.substring(firstTab + 1, secondTab));
        } catch (NumberFormatException e) {
          throw new IOException("Corrupt vocabulary artifact '" + artifactId + "'", e);
        }
        rows.add(new TermRow(line.substring(0, firstTab), count));
      }
    }
    return List.copyOf(rows);
  }

  /** Loads and verifies artifacts that were published before this process started. */
  private void loadExistingArtifacts() throws IOException {
    loadDictionaries();
    loadVocabularies();
  }

  /** Loads and verifies every published dictionary artifact. */
  private void loadDictionaries() throws IOException {
    for (String artifactId : store.list(DICTIONARIES_KIND)) {
      final DictionaryArtifactDescriptor descriptor;
      try (InputStream input = store.read(DICTIONARIES_KIND, artifactId,
          DICTIONARY_DESCRIPTOR)) {
        descriptor = DictionaryArtifactDescriptor.parseFrom(input);
      }
      requireListedIdentity(artifactId, descriptor.getArtifactId());
      formats.require(descriptor.getFormat());
      verify(DICTIONARIES_KIND, artifactId, DICTIONARY_DATA,
          descriptor.getByteSize(), descriptor.getArtifactHash());
      if (dictionaries.putIfAbsent(descriptor.getArtifactId(), descriptor) != null) {
        throw new IOException("Duplicate dictionary artifact id '"
            + descriptor.getArtifactId() + "'");
      }
    }
  }

  /** Loads and verifies every published vocabulary artifact. */
  private void loadVocabularies() throws IOException {
    for (String artifactId : store.list(VOCABULARIES_KIND)) {
      final VocabularyArtifactDescriptor descriptor;
      try (InputStream input = store.read(VOCABULARIES_KIND, artifactId,
          VOCABULARY_DESCRIPTOR)) {
        descriptor = VocabularyArtifactDescriptor.parseFrom(input);
      }
      requireListedIdentity(artifactId, descriptor.getArtifactId());
      if (!descriptor.getDictionaryArtifactId().isEmpty()) {
        requireDictionary(descriptor.getDictionaryArtifactId());
      }
      verify(VOCABULARIES_KIND, artifactId, VOCABULARY_DATA,
          descriptor.getByteSize(), descriptor.getArtifactHash());
      if (vocabularies.putIfAbsent(descriptor.getArtifactId(), descriptor) != null) {
        throw new IOException("Duplicate vocabulary artifact id '"
            + descriptor.getArtifactId() + "'");
      }
    }
  }

  /** Reads canonical headwords after verifying their artifact. */
  private List<String> readDictionaryHeadwords(String artifactId) throws IOException {
    final DictionaryArtifactDescriptor descriptor = requireDictionary(artifactId);
    verify(DICTIONARIES_KIND, artifactId, DICTIONARY_DATA,
        descriptor.getByteSize(), descriptor.getArtifactHash());
    final List<String> headwords = new ArrayList<>(descriptor.getEntryCount());
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(
        store.read(DICTIONARIES_KIND, artifactId, DICTIONARY_DATA), StandardCharsets.UTF_8))) {
      String line;
      while ((line = reader.readLine()) != null) {
        final int tab = line.indexOf('\t');
        if (tab <= 0 || line.indexOf('\t', tab + 1) >= 0) {
          throw new IOException("Corrupt canonical dictionary artifact '" + artifactId + "'");
        }
        headwords.add(line.substring(0, tab));
      }
    }
    if (headwords.size() != descriptor.getEntryCount()) {
      throw new IOException("Dictionary artifact '" + artifactId + "' declares "
          + descriptor.getEntryCount() + " entries but contains " + headwords.size());
    }
    return headwords;
  }

  /** Writes entries in stable headword order using the canonical TSV representation. */
  private void writeDictionary(List<DictionaryEntryData> entries, OutputStream data)
      throws IOException {
    final Map<String, DictionaryEntryData> stable = new TreeMap<>();
    for (DictionaryEntryData entry : entries) {
      stable.put(entry.headword(), entry);
    }
    final BufferedWriter writer =
        new BufferedWriter(new OutputStreamWriter(data, StandardCharsets.UTF_8));
    for (DictionaryEntryData entry : stable.values()) {
      writer.write(entry.headword());
      writer.write('\t');
      writer.write(entry.definition());
      writer.write('\n');
    }
    // Flush without closing: the caller owns the entry stream and its digest.
    writer.flush();
  }

  /** Rejects artifact operations when no root was configured. */
  private void requireEnabled() {
    if (!writesEnabled()) {
      throw new IllegalStateException(ARTIFACT_ROOT_KEY
          + " is not configured; vocabulary writes are disabled");
    }
  }

  /** Validates dictionary import metadata before decoding input. */
  private void validateImportStart(ImportDictionaryStart start) {
    if (start == null) {
      throw new IllegalArgumentException("dictionary import start must not be null");
    }
    formats.require(start.getFormat());
    requireTrimmed(start.getDisplayName(), "dictionary display_name");
    requireTrimmed(start.getProvenanceSummary(), "dictionary provenance_summary");
    validateOptional(start.hasSourceUri(), start.getSourceUri(), "dictionary source_uri");
    validateOptional(start.hasLicenseName(), start.getLicenseName(), "dictionary license_name");
    validateOptional(start.hasLicenseUri(), start.getLicenseUri(), "dictionary license_uri");
  }

  /** Validates vocabulary controls and the optional referenced dictionary. */
  private void validateLearningStart(LearnVocabularyStart start) {
    if (start == null) {
      throw new IllegalArgumentException("vocabulary learning start must not be null");
    }
    if (!start.getDictionaryArtifactId().isEmpty()) {
      requireDictionary(start.getDictionaryArtifactId());
    }
    requireTrimmed(start.getDisplayName(), "vocabulary display_name");
    requireTrimmed(start.getProvenanceSummary(), "vocabulary provenance_summary");
    if (start.getMinFrequency() < 1) {
      throw new IllegalArgumentException("min_frequency must be positive");
    }
    if (start.getMaxTerms() < 1 || start.getMaxTerms() > maxVocabularyTerms) {
      throw new IllegalArgumentException("max_terms must be between 1 and "
          + maxVocabularyTerms + ", was " + start.getMaxTerms());
    }
  }

  /** Validates one present proto3 optional string. */
  private void validateOptional(boolean present, String value, String name) {
    if (present) {
      requireTrimmed(value, name);
    }
  }

  /** Requires a trimmed, nonblank string. */
  private void requireTrimmed(String value, String name) {
    if (value == null || value.isBlank() || !value.equals(value.trim())) {
      throw new IllegalArgumentException(name + " must be trimmed and nonblank");
    }
  }

  /** Validates a generated artifact id and its expected kind prefix. */
  private void requireArtifactId(String id, String kind) {
    requireTrimmed(id, kind + " artifact_id");
    final String prefix = kind + "-";
    if (!id.startsWith(prefix) || id.length() != prefix.length() + 36) {
      throw new IllegalArgumentException("Invalid " + kind + " artifact_id '" + id + "'");
    }
    try {
      UUID.fromString(id.substring(prefix.length()));
    } catch (IllegalArgumentException e) {
      throw new IllegalArgumentException("Invalid " + kind + " artifact_id '" + id + "'", e);
    }
  }

  /** Requires a descriptor id to match the id it was published under. */
  private void requireListedIdentity(String publishedId, String descriptorId)
      throws IOException {
    if (!publishedId.equals(descriptorId)) {
      throw new IOException("Artifact descriptor id '" + descriptorId
          + "' does not match published id '" + publishedId + "'");
    }
  }

  /** Reads one positive configured limit bounded by a fixed ceiling. */
  private static int configuredPositiveInt(
      Map<String, String> configuration, String key, int defaultValue, int ceiling) {
    final String value = configuration.get(key);
    final int parsed;
    try {
      parsed = value == null ? defaultValue : Integer.parseInt(value);
    } catch (NumberFormatException e) {
      throw new IllegalArgumentException(key + " must be a positive integer", e);
    }
    if (parsed < 1 || parsed > ceiling) {
      throw new IllegalArgumentException(key + " must be between 1 and " + ceiling
          + ", was " + parsed);
    }
    return parsed;
  }

  /** Returns the UTF-8 byte length of a string. */
  private int utf8Length(String value) {
    return value.getBytes(StandardCharsets.UTF_8).length;
  }

  /** Converts a nonnegative value to the Java representation used by protobuf uint32 fields. */
  private int checkedUint32(long value, String name) {
    if (value < 0 || value > Integer.MAX_VALUE) {
      throw new IllegalArgumentException(name + " exceeds the supported Java int range: " + value);
    }
    return (int) value;
  }

  /** Returns the current wall-clock instant as a protobuf timestamp. */
  private Timestamp now() {
    final Instant now = Instant.now();
    return Timestamp.newBuilder().setSeconds(now.getEpochSecond()).setNanos(now.getNano()).build();
  }

  /** Verifies byte size and SHA-256 for one published artifact data entry. */
  private void verify(String kind, String artifactId, String entryName,
      int expectedSize, String expectedHash) throws IOException {
    final ArtifactDigests.SizedDigest digest;
    try (InputStream input = store.read(kind, artifactId, entryName)) {
      digest = ArtifactDigests.digest(input);
    }
    if (digest.size() != Integer.toUnsignedLong(expectedSize)) {
      throw new IOException("Artifact '" + artifactId + "' byte size mismatch: expected "
          + Integer.toUnsignedLong(expectedSize) + ", found " + digest.size());
    }
    if (!digest.hexDigest().equals(expectedHash)) {
      throw new IOException("Artifact '" + artifactId + "' SHA-256 mismatch");
    }
  }

}
