/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.opennlp.grpc.vocabulary;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.DirectoryStream;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.BasicFileAttributes;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import com.google.protobuf.MessageLite;
import com.google.protobuf.Timestamp;
import opennlp.embeddings.corpus.TermCount;
import opennlp.embeddings.corpus.VocabularyLearner;
import org.apache.opennlp.grpc.v1.DictionaryArtifactDescriptor;
import org.apache.opennlp.grpc.v1.ImportDictionaryStart;
import org.apache.opennlp.grpc.v1.LearnVocabularyStart;
import org.apache.opennlp.grpc.v1.OpenNlpDocument;
import org.apache.opennlp.grpc.v1.VocabularyArtifactDescriptor;

/**
 * Bounded, atomic disk store for imported dictionaries and learned vocabulary tables.
 *
 * <p>All artifact ids are generated by the server. Publication uses an atomic directory move
 * beneath one operator-configured root, so callers never select filesystem paths and readers
 * never observe a partial artifact.</p>
 */
public final class VocabularyArtifactStore {

  /** Default maximum encoded dictionary input size. */
  static final int DEFAULT_MAX_DICTIONARY_BYTES = 64 * 1024 * 1024;
  /** Default maximum number of normalized dictionary entries. */
  static final int DEFAULT_MAX_DICTIONARY_ENTRIES = 1_000_000;
  /** Default maximum documents in one vocabulary build. */
  static final int DEFAULT_MAX_CORPUS_DOCUMENTS = 100_000;
  /** Default maximum UTF-8 corpus text bytes in one vocabulary build. */
  static final int DEFAULT_MAX_CORPUS_BYTES = 100 * 1024 * 1024;
  /** Default maximum vocabulary terms, including dictionary terms. */
  static final int DEFAULT_MAX_VOCABULARY_TERMS = 1_000_000;
  /** Default maximum dictionary imports and vocabulary builds admitted at once. */
  static final int DEFAULT_MAX_CONCURRENT_WRITES = 1;

  private static final int MAX_DICTIONARY_BYTES_LIMIT = 1_073_741_824;
  private static final int MAX_DICTIONARY_ENTRIES_LIMIT = 10_000_000;
  private static final int MAX_CORPUS_DOCUMENTS_LIMIT = 1_000_000;
  private static final int MAX_CORPUS_BYTES_LIMIT = 1_073_741_824;
  private static final int MAX_VOCABULARY_TERMS_LIMIT = 10_000_000;
  private static final int MAX_CONCURRENT_WRITES_LIMIT = 32;
  private static final int MAX_ENTRY_BYTES = 1_048_576;
  static final String ARTIFACT_ROOT_KEY = "vocabulary.artifact_root";
  private static final String DICTIONARIES_DIRECTORY = "dictionaries";
  private static final String VOCABULARIES_DIRECTORY = "vocabularies";
  private static final String DICTIONARY_DATA = "entries.tsv";
  private static final String DICTIONARY_DESCRIPTOR = "dictionary.pb";
  private static final String VOCABULARY_DATA = "vocabulary.tsv";
  private static final String VOCABULARY_DESCRIPTOR = "vocabulary.pb";

  private final Path root;
  private final Path dictionariesDirectory;
  private final Path vocabulariesDirectory;
  private final DictionaryFormatRegistry formats;
  private final int maxDictionaryBytes;
  private final int maxDictionaryEntries;
  private final int maxCorpusDocuments;
  private final int maxCorpusBytes;
  private final int maxVocabularyTerms;
  private final int maxConcurrentWrites;
  private final Map<String, DictionaryArtifactDescriptor> dictionaries =
      new ConcurrentHashMap<>();
  private final Map<String, VocabularyArtifactDescriptor> vocabularies =
      new ConcurrentHashMap<>();

  /** Creates the store and verifies every artifact already present beneath the root. */
  private VocabularyArtifactStore(
      Path root,
      DictionaryFormatRegistry formats,
      int maxDictionaryBytes,
      int maxDictionaryEntries,
      int maxCorpusDocuments,
      int maxCorpusBytes,
      int maxVocabularyTerms,
      int maxConcurrentWrites) throws IOException {
    this.root = root;
    this.dictionariesDirectory = root == null ? null : root.resolve(DICTIONARIES_DIRECTORY);
    this.vocabulariesDirectory = root == null ? null : root.resolve(VOCABULARIES_DIRECTORY);
    this.formats = formats;
    this.maxDictionaryBytes = maxDictionaryBytes;
    this.maxDictionaryEntries = maxDictionaryEntries;
    this.maxCorpusDocuments = maxCorpusDocuments;
    this.maxCorpusBytes = maxCorpusBytes;
    this.maxVocabularyTerms = maxVocabularyTerms;
    this.maxConcurrentWrites = maxConcurrentWrites;
    if (root != null) {
      createStorageDirectory(root);
      createStorageDirectory(dictionariesDirectory);
      createStorageDirectory(vocabulariesDirectory);
      loadExistingArtifacts();
    }
  }

  /**
   * Creates a disabled or enabled store from server configuration.
   *
   * @param configuration Server configuration map.
   * @param formats Available dictionary format registry.
   * @return Configured store.
   * @throws IOException If an enabled artifact root cannot be created or verified.
   * @throws IllegalArgumentException If a configured limit is invalid.
   */
  public static VocabularyArtifactStore fromConfiguration(
      Map<String, String> configuration, DictionaryFormatRegistry formats) throws IOException {
    if (configuration == null) {
      throw new IllegalArgumentException("configuration must not be null");
    }
    if (formats == null) {
      throw new IllegalArgumentException("formats must not be null");
    }
    final String configuredRoot = configuration.get(ARTIFACT_ROOT_KEY);
    final Path root = configuredRoot == null || configuredRoot.isBlank()
        ? null : Path.of(configuredRoot).toAbsolutePath().normalize();
    return new VocabularyArtifactStore(
        root,
        formats,
        configuredPositiveInt(configuration, "vocabulary.max_dictionary_bytes",
            DEFAULT_MAX_DICTIONARY_BYTES, MAX_DICTIONARY_BYTES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_dictionary_entries",
            DEFAULT_MAX_DICTIONARY_ENTRIES, MAX_DICTIONARY_ENTRIES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_corpus_documents",
            DEFAULT_MAX_CORPUS_DOCUMENTS, MAX_CORPUS_DOCUMENTS_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_corpus_bytes",
            DEFAULT_MAX_CORPUS_BYTES, MAX_CORPUS_BYTES_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_vocabulary_terms",
            DEFAULT_MAX_VOCABULARY_TERMS, MAX_VOCABULARY_TERMS_LIMIT),
        configuredPositiveInt(configuration, "vocabulary.max_concurrent_writes",
            DEFAULT_MAX_CONCURRENT_WRITES, MAX_CONCURRENT_WRITES_LIMIT));
  }

  /** @return Whether write and download operations have a configured artifact root. */
  boolean writesEnabled() {
    return root != null;
  }

  /** @return Maximum encoded bytes accepted by one dictionary import. */
  int maxDictionaryBytes() {
    return maxDictionaryBytes;
  }

  /** @return Maximum normalized entries accepted by one dictionary import. */
  int maxDictionaryEntries() {
    return maxDictionaryEntries;
  }

  /** @return Maximum documents accepted by one vocabulary build. */
  int maxCorpusDocuments() {
    return maxCorpusDocuments;
  }

  /** @return Maximum UTF-8 corpus bytes accepted by one vocabulary build. */
  int maxCorpusBytes() {
    return maxCorpusBytes;
  }

  /** @return Maximum total terms accepted in one learned vocabulary. */
  int maxVocabularyTerms() {
    return maxVocabularyTerms;
  }

  /** @return Maximum dictionary imports and vocabulary builds admitted at once. */
  int maxConcurrentWrites() {
    return maxConcurrentWrites;
  }

  /**
   * Imports one complete bounded dictionary payload and publishes its canonical representation.
   *
   * @param start Import metadata and format selector.
   * @param encoded Complete encoded bytes.
   * @return Published artifact descriptor.
   * @throws IOException If parsing or atomic publication fails.
   * @throws IllegalArgumentException If the metadata, format, or payload bounds are invalid.
   */
  DictionaryArtifactDescriptor importDictionary(
      ImportDictionaryStart start, byte[] encoded) throws IOException {
    requireEnabled();
    validateImportStart(start);
    if (encoded == null) {
      throw new IllegalArgumentException("dictionary data must not be null");
    }
    if (encoded.length > maxDictionaryBytes) {
      throw new IllegalArgumentException("dictionary bytes " + encoded.length
          + " exceed configured maximum " + maxDictionaryBytes);
    }
    final DictionaryFormatProvider provider = formats.require(start.getFormat());
    final Map<String, DictionaryEntryData> decoded = new LinkedHashMap<>();
    try (InputStream input = new ByteArrayInputStream(encoded)) {
      provider.read(input, (headword, definition) -> {
        final DictionaryEntryData entry;
        try {
          entry = new DictionaryEntryData(headword, definition);
        } catch (IllegalArgumentException e) {
          throw new IOException("Invalid dictionary entry: " + e.getMessage(), e);
        }
        final int entryBytes = utf8Length(entry.headword()) + utf8Length(entry.definition());
        if (entryBytes > MAX_ENTRY_BYTES) {
          throw new IOException("Dictionary entry exceeds " + MAX_ENTRY_BYTES + " UTF-8 bytes");
        }
        decoded.putIfAbsent(entry.headword(), entry);
        if (decoded.size() > maxDictionaryEntries) {
          throw new IOException("dictionary entries exceed configured maximum "
              + maxDictionaryEntries);
        }
      });
    }
    if (decoded.isEmpty()) {
      throw new IllegalArgumentException("dictionary must contain at least one entry");
    }

    final String artifactId = "dictionary-" + UUID.randomUUID();
    final Path staging = createStaging(artifactId);
    try {
      final Path data = staging.resolve(DICTIONARY_DATA);
      writeDictionary(new ArrayList<>(decoded.values()), data);
      final long size = Files.size(data);
      final DictionaryArtifactDescriptor.Builder descriptor = DictionaryArtifactDescriptor
          .newBuilder()
          .setArtifactId(artifactId)
          .setDisplayName(start.getDisplayName())
          .setFormat(start.getFormat())
          .setEntryCount(decoded.size())
          .setArtifactHash(sha256(data))
          .setByteSize(checkedUint32(size, "dictionary artifact bytes"))
          .setProvenanceSummary(start.getProvenanceSummary())
          .setCreatedAt(now());
      if (start.hasSourceUri()) {
        descriptor.setSourceUri(start.getSourceUri());
      }
      if (start.hasLicenseName()) {
        descriptor.setLicenseName(start.getLicenseName());
      }
      if (start.hasLicenseUri()) {
        descriptor.setLicenseUri(start.getLicenseUri());
      }
      final DictionaryArtifactDescriptor result = descriptor.build();
      writeMessage(result, staging.resolve(DICTIONARY_DESCRIPTOR));
      publish(staging, dictionariesDirectory.resolve(artifactId));
      dictionaries.put(artifactId, result);
      return result;
    } catch (IOException | RuntimeException | Error failure) {
      deleteTreeSuppressing(staging, failure);
      throw failure;
    }
  }

  /**
   * Learns and atomically publishes a vocabulary over the supplied document shapes.
   *
   * @param start Learning configuration and dictionary identity.
   * @param documents Corpus documents whose raw text is counted.
   * @return Published vocabulary descriptor.
   * @throws IOException If artifact reading or publication fails.
   * @throws IllegalArgumentException If the controls, dictionary id, or corpus are invalid.
   */
  VocabularyArtifactDescriptor learnVocabulary(
      LearnVocabularyStart start, List<OpenNlpDocument> documents) throws IOException {
    requireEnabled();
    validateLearningStart(start);
    if (documents == null) {
      throw new IllegalArgumentException("corpus documents must not be null");
    }
    if (documents.isEmpty()) {
      throw new IllegalArgumentException("corpus must contain at least one document");
    }
    if (documents.size() > maxCorpusDocuments) {
      throw new IllegalArgumentException("corpus documents " + documents.size()
          + " exceed configured maximum " + maxCorpusDocuments);
    }
    final List<String> texts = new ArrayList<>(documents.size());
    long corpusBytes = 0;
    for (OpenNlpDocument document : documents) {
      if (document == null) {
        throw new IllegalArgumentException("corpus documents must not contain null");
      }
      if (document.getRawText().isBlank()) {
        throw new IllegalArgumentException("corpus document raw_text must not be blank");
      }
      corpusBytes += utf8Length(document.getRawText());
      if (corpusBytes > maxCorpusBytes) {
        throw new IllegalArgumentException("corpus bytes " + corpusBytes
            + " exceed configured maximum " + maxCorpusBytes);
      }
      texts.add(document.getRawText());
    }

    requireDictionary(start.getDictionaryArtifactId());
    final List<String> headwords = readDictionaryHeadwords(start.getDictionaryArtifactId());
    final List<TermCount> terms = new VocabularyLearner(
        start.getMinFrequency(), start.getMaxTerms()).learn(texts, headwords);
    if (terms.size() > maxVocabularyTerms) {
      throw new IllegalArgumentException("learned vocabulary terms " + terms.size()
          + " exceed configured maximum " + maxVocabularyTerms);
    }
    final long dictionaryTerms = terms.stream().filter(TermCount::fromDictionary).count();
    final String artifactId = "vocabulary-" + UUID.randomUUID();
    final Path staging = createStaging(artifactId);
    try {
      final Path data = staging.resolve(VOCABULARY_DATA);
      TermCount.writeTsv(terms, data);
      final long size = Files.size(data);
      final VocabularyArtifactDescriptor result = VocabularyArtifactDescriptor.newBuilder()
          .setArtifactId(artifactId)
          .setDisplayName(start.getDisplayName())
          .setDictionaryArtifactId(start.getDictionaryArtifactId())
          .setTermCount(terms.size())
          .setDictionaryTermCount(checkedUint32(dictionaryTerms, "dictionary term count"))
          .setCorpusTermCount(checkedUint32(terms.size() - dictionaryTerms, "corpus term count"))
          .setMinFrequency(start.getMinFrequency())
          .setMaxTerms(start.getMaxTerms())
          .setArtifactHash(sha256(data))
          .setByteSize(checkedUint32(size, "vocabulary artifact bytes"))
          .setProvenanceSummary(start.getProvenanceSummary())
          .setCreatedAt(now())
          .build();
      writeMessage(result, staging.resolve(VOCABULARY_DESCRIPTOR));
      publish(staging, vocabulariesDirectory.resolve(artifactId));
      vocabularies.put(artifactId, result);
      return result;
    } catch (IOException | RuntimeException | Error failure) {
      deleteTreeSuppressing(staging, failure);
      throw failure;
    }
  }

  /**
   * Resolves one dictionary descriptor.
   *
   * @param artifactId Server-owned artifact id.
   * @return Descriptor.
   * @throws IllegalArgumentException If the id is invalid or unknown.
   */
  DictionaryArtifactDescriptor requireDictionary(String artifactId) {
    requireArtifactId(artifactId, "dictionary");
    final DictionaryArtifactDescriptor descriptor = dictionaries.get(artifactId);
    if (descriptor == null) {
      throw new UnknownVocabularyArtifactException(
          "Unknown dictionary artifact '" + artifactId + "'");
    }
    return descriptor;
  }

  /**
   * Resolves one vocabulary descriptor.
   *
   * @param artifactId Server-owned artifact id.
   * @return Descriptor.
   * @throws IllegalArgumentException If the id is invalid or unknown.
   */
  VocabularyArtifactDescriptor requireVocabulary(String artifactId) {
    requireArtifactId(artifactId, "vocabulary");
    final VocabularyArtifactDescriptor descriptor = vocabularies.get(artifactId);
    if (descriptor == null) {
      throw new UnknownVocabularyArtifactException(
          "Unknown vocabulary artifact '" + artifactId + "'");
    }
    return descriptor;
  }

  /**
   * Reads and verifies the exact TSV bytes for one learned vocabulary.
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return Exact artifact bytes.
   * @throws IOException If reading or integrity verification fails.
   * @throws IllegalArgumentException If the artifact id is invalid or unknown.
   */
  byte[] readVocabulary(String artifactId) throws IOException {
    try (InputStream input = openVocabulary(artifactId)) {
      return input.readAllBytes();
    }
  }

  /**
   * Opens a verified stream over the exact TSV bytes for one learned vocabulary.
   *
   * @param artifactId Server-owned vocabulary artifact id.
   * @return Verified artifact stream. The caller must close it.
   * @throws IOException If opening or integrity verification fails.
   * @throws IllegalArgumentException If the artifact id is invalid or unknown.
   */
  InputStream openVocabulary(String artifactId) throws IOException {
    requireEnabled();
    final VocabularyArtifactDescriptor descriptor = requireVocabulary(artifactId);
    final Path data = vocabulariesDirectory.resolve(artifactId).resolve(VOCABULARY_DATA);
    verifyData(data, descriptor.getByteSize(), descriptor.getArtifactHash(), artifactId);
    return Files.newInputStream(data);
  }

  /** Loads and verifies artifacts that were published before this process started. */
  private void loadExistingArtifacts() throws IOException {
    loadDictionaries();
    loadVocabularies();
  }

  /** Loads and verifies every published dictionary artifact. */
  private void loadDictionaries() throws IOException {
    try (DirectoryStream<Path> stream = Files.newDirectoryStream(dictionariesDirectory)) {
      for (Path directory : stream) {
        if (!Files.isDirectory(directory) || Files.isSymbolicLink(directory)) {
          throw new IOException("Unexpected dictionary artifact entry: " + directory);
        }
        final Path descriptorFile = directory.resolve(DICTIONARY_DESCRIPTOR);
        final DictionaryArtifactDescriptor descriptor;
        try (InputStream input = Files.newInputStream(descriptorFile)) {
          descriptor = DictionaryArtifactDescriptor.parseFrom(input);
        }
        requireDirectoryIdentity(directory, descriptor.getArtifactId());
        formats.require(descriptor.getFormat());
        verifyData(directory.resolve(DICTIONARY_DATA), descriptor.getByteSize(),
            descriptor.getArtifactHash(), descriptor.getArtifactId());
        if (dictionaries.putIfAbsent(descriptor.getArtifactId(), descriptor) != null) {
          throw new IOException("Duplicate dictionary artifact id '"
              + descriptor.getArtifactId() + "'");
        }
      }
    }
  }

  /** Loads and verifies every published vocabulary artifact. */
  private void loadVocabularies() throws IOException {
    try (DirectoryStream<Path> stream = Files.newDirectoryStream(vocabulariesDirectory)) {
      for (Path directory : stream) {
        if (!Files.isDirectory(directory) || Files.isSymbolicLink(directory)) {
          throw new IOException("Unexpected vocabulary artifact entry: " + directory);
        }
        final VocabularyArtifactDescriptor descriptor;
        try (InputStream input = Files.newInputStream(directory.resolve(VOCABULARY_DESCRIPTOR))) {
          descriptor = VocabularyArtifactDescriptor.parseFrom(input);
        }
        requireDirectoryIdentity(directory, descriptor.getArtifactId());
        requireDictionary(descriptor.getDictionaryArtifactId());
        verifyData(directory.resolve(VOCABULARY_DATA), descriptor.getByteSize(),
            descriptor.getArtifactHash(), descriptor.getArtifactId());
        if (vocabularies.putIfAbsent(descriptor.getArtifactId(), descriptor) != null) {
          throw new IOException("Duplicate vocabulary artifact id '"
              + descriptor.getArtifactId() + "'");
        }
      }
    }
  }

  /** Reads canonical headwords after verifying their artifact. */
  private List<String> readDictionaryHeadwords(String artifactId) throws IOException {
    final DictionaryArtifactDescriptor descriptor = requireDictionary(artifactId);
    final Path data = dictionariesDirectory.resolve(artifactId).resolve(DICTIONARY_DATA);
    verifyData(data, descriptor.getByteSize(), descriptor.getArtifactHash(), artifactId);
    final List<String> headwords = new ArrayList<>(descriptor.getEntryCount());
    try (BufferedReader reader = Files.newBufferedReader(data, StandardCharsets.UTF_8)) {
      String line;
      while ((line = reader.readLine()) != null) {
        final int tab = line.indexOf('\t');
        if (tab <= 0 || line.indexOf('\t', tab + 1) >= 0) {
          throw new IOException("Corrupt canonical dictionary artifact '" + artifactId + "'");
        }
        headwords.add(line.substring(0, tab));
      }
    }
    if (headwords.size() != descriptor.getEntryCount()) {
      throw new IOException("Dictionary artifact '" + artifactId + "' declares "
          + descriptor.getEntryCount() + " entries but contains " + headwords.size());
    }
    return headwords;
  }

  /** Writes entries in stable headword order using the canonical TSV representation. */
  private void writeDictionary(List<DictionaryEntryData> entries, Path data)
      throws IOException {
    final Map<String, DictionaryEntryData> stable = new TreeMap<>();
    for (DictionaryEntryData entry : entries) {
      stable.put(entry.headword(), entry);
    }
    try (BufferedWriter writer = Files.newBufferedWriter(data, StandardCharsets.UTF_8)) {
      for (DictionaryEntryData entry : stable.values()) {
        writer.write(entry.headword());
        writer.write('\t');
        writer.write(entry.definition());
        writer.write('\n');
      }
    }
  }

  /** Creates an artifact staging directory beneath the configured root. */
  private Path createStaging(String artifactId) throws IOException {
    final Path staging = root.resolve(".staging-" + artifactId);
    return Files.createDirectory(staging);
  }

  /** Publishes one completed staging directory atomically. */
  private void publish(Path staging, Path destination) throws IOException {
    try {
      Files.move(staging, destination, StandardCopyOption.ATOMIC_MOVE);
    } catch (AtomicMoveNotSupportedException e) {
      throw new IOException("Artifact root does not support atomic directory publication", e);
    }
  }

  /** Creates and validates one real storage directory. */
  private void createStorageDirectory(Path directory) throws IOException {
    Files.createDirectories(directory);
    if (!Files.isDirectory(directory) || Files.isSymbolicLink(directory)) {
      throw new IOException("Vocabulary artifact path must be a real directory: " + directory);
    }
  }

  /** Rejects artifact operations when no root was configured. */
  private void requireEnabled() {
    if (!writesEnabled()) {
      throw new IllegalStateException(ARTIFACT_ROOT_KEY
          + " is not configured; vocabulary writes are disabled");
    }
  }

  /** Validates dictionary import metadata before decoding input. */
  private void validateImportStart(ImportDictionaryStart start) {
    if (start == null) {
      throw new IllegalArgumentException("dictionary import start must not be null");
    }
    formats.require(start.getFormat());
    requireTrimmed(start.getDisplayName(), "dictionary display_name");
    requireTrimmed(start.getProvenanceSummary(), "dictionary provenance_summary");
    validateOptional(start.hasSourceUri(), start.getSourceUri(), "dictionary source_uri");
    validateOptional(start.hasLicenseName(), start.getLicenseName(), "dictionary license_name");
    validateOptional(start.hasLicenseUri(), start.getLicenseUri(), "dictionary license_uri");
  }

  /** Validates vocabulary controls and the referenced dictionary. */
  private void validateLearningStart(LearnVocabularyStart start) {
    if (start == null) {
      throw new IllegalArgumentException("vocabulary learning start must not be null");
    }
    requireDictionary(start.getDictionaryArtifactId());
    requireTrimmed(start.getDisplayName(), "vocabulary display_name");
    requireTrimmed(start.getProvenanceSummary(), "vocabulary provenance_summary");
    if (start.getMinFrequency() < 1) {
      throw new IllegalArgumentException("min_frequency must be positive");
    }
    if (start.getMaxTerms() < 1 || start.getMaxTerms() > maxVocabularyTerms) {
      throw new IllegalArgumentException("max_terms must be between 1 and "
          + maxVocabularyTerms + ", was " + start.getMaxTerms());
    }
  }

  /** Validates one present proto3 optional string. */
  private void validateOptional(boolean present, String value, String name) {
    if (present) {
      requireTrimmed(value, name);
    }
  }

  /** Requires a trimmed, nonblank string. */
  private void requireTrimmed(String value, String name) {
    if (value == null || value.isBlank() || !value.equals(value.trim())) {
      throw new IllegalArgumentException(name + " must be trimmed and nonblank");
    }
  }

  /** Validates a generated artifact id and its expected kind prefix. */
  private void requireArtifactId(String id, String kind) {
    requireTrimmed(id, kind + " artifact_id");
    final String prefix = kind + "-";
    if (!id.startsWith(prefix) || id.length() != prefix.length() + 36) {
      throw new IllegalArgumentException("Invalid " + kind + " artifact_id '" + id + "'");
    }
    try {
      UUID.fromString(id.substring(prefix.length()));
    } catch (IllegalArgumentException e) {
      throw new IllegalArgumentException("Invalid " + kind + " artifact_id '" + id + "'", e);
    }
  }

  /** Requires a descriptor id to match its containing directory. */
  private void requireDirectoryIdentity(Path directory, String artifactId)
      throws IOException {
    if (!directory.getFileName().toString().equals(artifactId)) {
      throw new IOException("Artifact descriptor id '" + artifactId
          + "' does not match directory " + directory);
    }
  }

  /** Reads one positive configured limit bounded by a fixed ceiling. */
  private static int configuredPositiveInt(
      Map<String, String> configuration, String key, int defaultValue, int ceiling) {
    final String value = configuration.get(key);
    final int parsed;
    try {
      parsed = value == null ? defaultValue : Integer.parseInt(value);
    } catch (NumberFormatException e) {
      throw new IllegalArgumentException(key + " must be a positive integer", e);
    }
    if (parsed < 1 || parsed > ceiling) {
      throw new IllegalArgumentException(key + " must be between 1 and " + ceiling
          + ", was " + parsed);
    }
    return parsed;
  }

  /** Returns the UTF-8 byte length of a string. */
  private int utf8Length(String value) {
    return value.getBytes(StandardCharsets.UTF_8).length;
  }

  /** Converts a nonnegative value to the Java representation used by protobuf uint32 fields. */
  private int checkedUint32(long value, String name) {
    if (value < 0 || value > Integer.MAX_VALUE) {
      throw new IllegalArgumentException(name + " exceeds the supported Java int range: " + value);
    }
    return (int) value;
  }

  /** Returns the current wall-clock instant as a protobuf timestamp. */
  private Timestamp now() {
    final Instant now = Instant.now();
    return Timestamp.newBuilder().setSeconds(now.getEpochSecond()).setNanos(now.getNano()).build();
  }

  /** Writes one protobuf message to a new artifact file. */
  private void writeMessage(MessageLite message, Path destination) throws IOException {
    try (OutputStream output = Files.newOutputStream(destination)) {
      message.writeTo(output);
    }
  }

  /** Verifies regular-file shape, byte size, and SHA-256 for one artifact data file. */
  private void verifyData(Path data, int expectedSize, String expectedHash, String id)
      throws IOException {
    if (!Files.isRegularFile(data) || Files.isSymbolicLink(data)) {
      throw new IOException("Artifact '" + id + "' data is not a regular file: " + data);
    }
    final long actualSize = Files.size(data);
    if (actualSize != Integer.toUnsignedLong(expectedSize)) {
      throw new IOException("Artifact '" + id + "' byte size mismatch: expected "
          + Integer.toUnsignedLong(expectedSize) + ", found " + actualSize);
    }
    final String actualHash = sha256(data);
    if (!actualHash.equals(expectedHash)) {
      throw new IOException("Artifact '" + id + "' SHA-256 mismatch");
    }
  }

  /** Computes a lowercase hexadecimal SHA-256 digest. */
  private String sha256(Path file) throws IOException {
    final MessageDigest digest;
    try {
      digest = MessageDigest.getInstance("SHA-256");
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("JVM lacks SHA-256", e);
    }
    try (InputStream input = Files.newInputStream(file)) {
      final byte[] buffer = new byte[8192];
      int read;
      while ((read = input.read(buffer)) >= 0) {
        if (read > 0) {
          digest.update(buffer, 0, read);
        }
      }
    }
    final char[] alphabet = "0123456789abcdef".toCharArray();
    final byte[] bytes = digest.digest();
    final StringBuilder hex = new StringBuilder(bytes.length * 2);
    for (byte value : bytes) {
      hex.append(alphabet[(value >>> 4) & 0x0f]);
      hex.append(alphabet[value & 0x0f]);
    }
    return hex.toString();
  }

  /** Deletes a failed staging tree and suppresses cleanup errors on the original failure. */
  private void deleteTreeSuppressing(Path root, Throwable failure) {
    if (root == null || !Files.exists(root)) {
      return;
    }
    try {
      Files.walkFileTree(root, new SimpleFileVisitor<>() {
        @Override
        public FileVisitResult visitFile(Path file, BasicFileAttributes attributes)
            throws IOException {
          Files.delete(file);
          return FileVisitResult.CONTINUE;
        }

        @Override
        public FileVisitResult postVisitDirectory(Path directory, IOException error)
            throws IOException {
          if (error != null) {
            throw error;
          }
          Files.delete(directory);
          return FileVisitResult.CONTINUE;
        }
      });
    } catch (IOException cleanupFailure) {
      failure.addSuppressed(cleanupFailure);
    }
  }
}
