/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Analyzes documents, builds a TurboQuant index, and searches it through gRPC.
// Go twin of the Python quickstart, using stubs generated by ./generate.sh.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"

	opennlpv1 "opennlp-grpc-go-example/gen/opennlpv1"
)

var corpus = [][2]string{
	{"habeas", "The writ of habeas corpus protects a prisoner from unlawful detention. " +
		"A court may order the custodian to release the prisoner."},
	{"appeal", "The appellate court reviews the trial record for reversible error. " +
		"A timely notice preserves the right to appeal."},
	{"zoning", "A city may regulate rooftop apiaries through its zoning code. " +
		"The applicant requested a variance for three beehives."},
}

var baseSteps = []opennlpv1.PipelineStep{
	opennlpv1.PipelineStep_PIPELINE_STEP_LANGUAGE_DETECT,
	opennlpv1.PipelineStep_PIPELINE_STEP_SENTENCE_DETECT,
	opennlpv1.PipelineStep_PIPELINE_STEP_TOKENIZE,
	opennlpv1.PipelineStep_PIPELINE_STEP_POS_TAG,
	opennlpv1.PipelineStep_PIPELINE_STEP_LEMMATIZE,
	opennlpv1.PipelineStep_PIPELINE_STEP_STEM,
	opennlpv1.PipelineStep_PIPELINE_STEP_TERM_VECTOR,
}

func main() {
	target := flag.String("target", "localhost:7071", "gRPC server host:port")
	embeddingModel := flag.String("embedding-model",
		"", "logical embedding model id; inferred when exactly one is configured")
	cleanup := flag.Bool("cleanup", false, "delete the process-local index after displaying results")
	flag.Parse()

	if err := run(*target, *embeddingModel, *cleanup); err != nil {
		if rpc, ok := status.FromError(err); ok && rpc.Code() != 0 {
			fmt.Fprintf(os.Stderr, "gRPC %s: %s\n", rpc.Code(), rpc.Message())
		} else {
			fmt.Fprintln(os.Stderr, err)
		}
		os.Exit(1)
	}
}

func run(target, requestedModel string, cleanup bool) error {
	conn, err := grpc.NewClient(target, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return err
	}
	defer conn.Close()
	analysis := opennlpv1.NewOpenNlpAnalysisServiceClient(conn)
	search := opennlpv1.NewOpenNlpSearchServiceClient(conn)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	info, err := analysis.GetServiceInfo(ctx, &opennlpv1.GetServiceInfoRequest{})
	cancel()
	if err != nil {
		return err
	}
	fmt.Printf("Connected to OpenNLP %s, API %s, service %s\n",
		info.GetOpennlpVersion(), info.GetApiVersion(), info.GetServiceVersion())
	fmt.Printf("Server text limit: %d UTF-8 bytes\n", info.GetMaxTextBytes())

	modelID, err := selectEmbeddingModel(analysis, requestedModel)
	if err != nil {
		return err
	}
	fmt.Println("Embedding model:", modelID)

	documents, err := analyzeDocuments(analysis, modelID)
	if err != nil {
		return err
	}
	fmt.Printf("Analyzed %d documents\n", len(documents))
	printAnalysis(documents)

	ctx, cancel = context.WithTimeout(context.Background(), 60*time.Second)
	created, err := search.IndexDocuments(ctx, &opennlpv1.IndexDocumentsRequest{
		DisplayName: "Go quickstart corpus",
		Documents:   documents,
		Embedding:   &opennlpv1.EmbeddingSelector{ModelId: modelID},
		Provider: &opennlpv1.SearchProviderSelector{
			Kind: &opennlpv1.SearchProviderSelector_Standard{
				Standard: opennlpv1.StandardSearchProvider_STANDARD_SEARCH_PROVIDER_TURBO_QUANT,
			},
		},
	})
	cancel()
	if err != nil {
		return err
	}
	indexID := created.GetIndex().GetIndexId()
	fmt.Printf("\nTurboQuant index %s: %d documents, %d chunks\n",
		indexID, created.GetIndexedDocuments(), created.GetIndexedChunks())
	if !created.GetIndex().GetSupportsAllHits() {
		return fmt.Errorf("the TurboQuant index did not advertise exhaustive search")
	}

	searchErr := searchAll(search, indexID)
	if cleanup {
		ctx, cancel = context.WithTimeout(context.Background(), 10*time.Second)
		deleted, err := search.DeleteSearchIndex(ctx,
			&opennlpv1.DeleteSearchIndexRequest{IndexId: indexID})
		cancel()
		if err != nil {
			return err
		}
		if !deleted.GetDeleted() {
			return fmt.Errorf("temporary index %s was not deleted", indexID)
		}
		fmt.Printf("\nDeleted temporary index %s\n", indexID)
	}
	return searchErr
}

func selectEmbeddingModel(
	analysis opennlpv1.OpenNlpAnalysisServiceClient, requested string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	response, err := analysis.ListModelBundles(ctx, &opennlpv1.ListModelBundlesRequest{})
	if err != nil {
		return "", err
	}
	var models []string
	for _, bundle := range response.GetBundles() {
		for _, model := range bundle.GetModels() {
			if model.GetEmbeddingDimension() > 0 && !slices.Contains(models, model.GetName()) {
				models = append(models, model.GetName())
			}
		}
	}
	slices.Sort(models)
	if requested != "" {
		if !slices.Contains(models, requested) {
			available := "none"
			if len(models) > 0 {
				available = strings.Join(models, ", ")
			}
			return "", fmt.Errorf("embedding model %q is not configured; available: %s",
				requested, available)
		}
		return requested, nil
	}
	switch len(models) {
	case 1:
		return models[0], nil
	case 0:
		return "", fmt.Errorf("the server has no embedding model; configure one before running search")
	default:
		return "", fmt.Errorf("the server has several embedding models; "+
			"pass -embedding-model with one of: %s", strings.Join(models, ", "))
	}
}

func analyzeDocuments(
	analysis opennlpv1.OpenNlpAnalysisServiceClient, modelID string) ([]*opennlpv1.OpenNlpDocument, error) {
	profile := &opennlpv1.AnalysisProfile{
		Steps: baseSteps,
		Stemmer: &opennlpv1.StemmerSpec{
			Algorithm: opennlpv1.StemmerAlgorithm_STEMMER_ALGORITHM_SNOWBALL,
			Language:  proto.String("en"),
		},
		TermVector: &opennlpv1.TermVectorSpec{
			Mode: opennlpv1.TermVectorMode_TERM_VECTOR_MODE_FULL,
			SourceLayer: &opennlpv1.LayerIdentity{
				Kind: &opennlpv1.LayerIdentity_Standard{
					Standard: opennlpv1.StandardLayer_STANDARD_LAYER_LEMMAS,
				},
			},
		},
	}
	chunkConfigs := []*opennlpv1.ChunkEmbedConfigEntry{
		{
			ConfigId:          "sentences",
			ResultSetName:     proto.String("Sentence chunks"),
			EmbeddingModelIds: []string{modelID},
			Chunking: &opennlpv1.ChunkingSpec{
				Strategy: &opennlpv1.ChunkingStrategySelector{
					Kind: &opennlpv1.ChunkingStrategySelector_Standard{
						Standard: opennlpv1.StandardChunkingStrategy_STANDARD_CHUNKING_STRATEGY_SENTENCE,
					},
				},
			},
		},
		{
			ConfigId:          "token-windows",
			ResultSetName:     proto.String("Eight-token windows"),
			EmbeddingModelIds: []string{modelID},
			Chunking: &opennlpv1.ChunkingSpec{
				Strategy: &opennlpv1.ChunkingStrategySelector{
					Kind: &opennlpv1.ChunkingStrategySelector_Standard{
						Standard: opennlpv1.StandardChunkingStrategy_STANDARD_CHUNKING_STRATEGY_TOKEN,
					},
				},
				ChunkSize:    8,
				ChunkOverlap: 2,
			},
		},
	}
	var documents []*opennlpv1.OpenNlpDocument
	for _, entry := range corpus {
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		response, err := analysis.AnalyzeDocument(ctx, &opennlpv1.AnalyzeDocumentRequest{
			Document:          &opennlpv1.OpenNlpDocument{DocId: entry[0], RawText: entry[1]},
			Profile:           profile,
			Options:           &opennlpv1.AnalysisOptions{IncludeProbabilities: true},
			ChunkEmbedConfigs: chunkConfigs,
		})
		cancel()
		if err != nil {
			return nil, err
		}
		documents = append(documents, response.GetDocument())
	}
	return documents, nil
}

func printAnalysis(documents []*opennlpv1.OpenNlpDocument) {
	fmt.Printf("\nDocument analysis\n")
	for _, document := range documents {
		analytics := document.GetAnalytics()
		var layerIDs []string
		for _, layer := range document.GetLayers().GetLayers() {
			layerIDs = append(layerIDs, layer.GetId())
		}
		fmt.Printf("  %s: %d sentences, %d tokens, %d unique lemmas\n",
			document.GetDocId(), analytics.GetTotalSentences(),
			analytics.GetTotalTokens(), analytics.GetUniqueLemmaCount())
		var tokens []string
		for _, token := range document.GetSentences()[0].GetTokens() {
			if len(tokens) == 8 {
				break
			}
			tokens = append(tokens,
				fmt.Sprintf("%s/%s/%s", token.GetText(), token.GetPosTag(), token.GetLemma()))
		}
		fmt.Println("    first tokens:", strings.Join(tokens, " "))
		fmt.Println("    layers:", strings.Join(layerIDs, ", "))
	}
}

func searchAll(search opennlpv1.OpenNlpSearchServiceClient, indexID string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	response, err := search.SearchIndex(ctx, &opennlpv1.SearchIndexRequest{
		IndexId: indexID,
		QueryKind: &opennlpv1.SearchIndexRequest_Query{
			Query: &opennlpv1.OpenNlpDocument{
				DocId:   "query-1",
				RawText: "Which court remedy protects a prisoner from unlawful custody?",
			},
		},
		ResultLimit: &opennlpv1.SearchIndexRequest_AllHits{AllHits: true},
	})
	if err != nil {
		return err
	}
	fmt.Printf("\nSearch results (%d exhaustive hits)\n", len(response.GetHits()))
	for rank, hit := range response.GetHits() {
		fmt.Printf("  %2d. %+.4f  %s/%s: %s\n", rank+1, hit.GetScore(),
			hit.GetDocumentId(), hit.GetChunkGroupId(), hit.GetIndexedText())
	}
	if response.GetTruncated() {
		fmt.Println("  Results were truncated by the server response-byte limit.")
	}
	return nil
}
