model.location=/home/joy/grpc/opennlp-sandbox/opennlp-grpc/models
model.recursive=true

model.sentdetect.wildcard.pattern=opennlp-models-sentdetect-*.jar
model.tokenize.wildcard.pattern=opennlp-models-tokenize-*.jar
model.pos.wildcard.pattern=opennlp-models-pos-*.jar

server.enable_reflection=true